
cloud:
  aws:
    s3:
      bucket: ming-green-sample
      stack.auto:false
      region.static:ap-northeast-2
      credentials:
        accessKey: AKIAYQYNGKB7YNLTNSED
        secretKey: Jw83b120xiuP+LlPJp04BcpFY6CVcUXnlTBfBqXj